### ISSUE TITLE
Rate exceeded on Subscription call

### ISSUE THREAD

**Issue by MathieuGilbert** [amaabca/cloudwatch_loggly#5]
We have ~127 lambdas in our account, and the Subscribe lambda is throwing the following exception:

```
{
  "errorMessage": "Rate exceeded",
  "errorType": "Function<Aws::Lambda::Errors::ThrottlingException>",
  "stackTrace": [
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'",
    "/var/runtime/gems/aws-sdk-core-3.47.0/lib/seahorse/client/request.rb:70:in `send_request'",
    "/var/runtime/gems/aws-sdk-lambda-1.19.0/lib/aws-sdk-lambda/client.rb:2330:in `list_tags'",
    "/var/task/lambda/function.rb:89:in `fetch_tags!'",
    "/var/task/lambda/function.rb:51:in `initialize'",
    "/var/task/lambda/function.rb:13:in `new'",
    "/var/task/lambda/function.rb:13:in `block in all'",
    "/var/task/lambda/function.rb:12:in `map'",
    "/var/task/lambda/function.rb:12:in `all'",
    "/var/task/lambda/function.rb:29:in `subscribe_all!'",
    "/var/task/handler.rb:13:in `handle'"
  ]
}
```

I update to the latest version and re-ran but that did not fix it. We now have some lambdas with no subscription, some with the old one, and some with the new one.

It looks like it's the `lambda.list_tags` call that happens for each lambda on init that eventually hits the rate limit. Is there some way to add retries with backoff for calls that will hit limits as the lambda count scales up?

**Comment by jessedoyle** [comment]
We could get smart with exponential backoff if we hit an API throttle overhead. 

The main concern I would have is that it opens the potential for inconsistent state during the subscription call (i.e. what would happen if we rescue an API throttle exception for a lambda, but its tags include an override for a parameter value?).

I'll take a look and see if these are soft limits in AWS - I know that in many cases, API rate limits can be increased by opening a support ticket.

We may also be able to optimize the call to `list_tags`. It's possible that we're calling it more often than we should - I'll look into this as well.

**Comment by jessedoyle** [comment]
So, the AWS Ruby SDK performs up to 3 retries for rate limit throttling by default: https://github.com/aws/aws-sdk-ruby/blob/02d28b7b0a2ece1af13e129f0b054480bd37f733/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L32.

In this case, the request would have been throttled 3 times. It does [look like the SDK has a default delay of 0s between requests](https://github.com/aws/aws-sdk-ruby/blob/02d28b7b0a2ece1af13e129f0b054480bd37f733/gems/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L43), I'll see if we can play with that number.
